name: Test libfdu
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone code
        uses: actions/checkout@v2
      -
        name: prepare env
        env:
          SECRETS_UID_PWD: ${{ secrets.UID_PWD }}
        run: echo $SECRETS_UID_PWD | base64 -d > .env
      -
        name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      -
        name: run test
        env:
          RUST_BACKTRACE: 1
        run: cargo test -- --test-threads=1
